// frame/vue-side/src/components/End.vue
<template>
  <div>
    <h2>You should use Vue.js if:</h2>
    <div>
      <li>You're looking for a <strong>small, lightweight</strong> framework</li>
      <li>You're making a relatively <strong>simple</strong> application</li>
      <li>You want to be able to <strong>easily learn</strong> the framework</li>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'End'
  }
</script>

<style scoped>
  div {
    background: #4bb883;
    color: white;
    display: flex;
    flex-direction: column;
    text-shadow: 0px 1px 0px rgba(0,0,0,0.5);
    text-align: center;
    padding: 20px 0 30px;
  }
  h2 {
    margin-bottom: 10px;
  }
</style>

// frame/react-side/src/components/End/End.js
import React from 'react';
import './End.css';

const End = () => (
  <div className="end">
    <h2>You should use React if:</h2>
    <div className="end">
      <li>You're looking for a <strong>powerful</strong> framework</li>
      <li>You're making a <strong>complex</strong> application</li>
      <li>You want <strong>extensive community support</strong></li>
    </div>
  </div>
)

export default End;
